### ISSUE TITLE
README out of date

### ISSUE THREAD

**Issue by scragg0x** [RediSearch/RediSearchBenchmark#5]
It appears head of master is trying to load a reddit json file, I had to checkout an old commit to get things to work.
What is `scores.csv` and where can I get it, how is it used in the bench?
What versions of Elasticsearch are supported by this benchmark?

**Comment by filipecosta90** [comment]
@scragg0x this benchmark tool was updated to use the latest elastic driver and is compatible with Elastic8 and RediSearch v2.6.
The readme was updated with the required steps to run the benchmarks
